# Generated by Django 4.2.23 on 2025-09-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-contact_date'], 'verbose_name': 'Contact Inquiry', 'verbose_name_plural': 'Contact Inquiries'},
        ),
        migrations.AddField(
            model_name='contact',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('under_50m', 'Under ₦50M'), ('50m_100m', '₦50M - ₦100M'), ('100m_200m', '₦100M - ₦200M'), ('200m_500m', '₦200M - ₦500M'), ('500m_1b', '₦500M - ₦1B'), ('over_1b', 'Over ₦1B'), ('not_specified', 'Not Specified')], max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('property', 'Property Inquiry'), ('viewing', 'Property Viewing'), ('consultation', 'Consultation Request'), ('support', 'Support')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for staff'),
        ),
        migrations.AddField(
            model_name='contact',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('villa', 'Villa'), ('land', 'Land'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('contacted', 'Contacted'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='timeline',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediately'), ('1_month', 'Within 1 Month'), ('3_months', 'Within 3 Months'), ('6_months', 'Within 6 Months'), ('1_year', 'Within 1 Year'), ('flexible', 'Flexible')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='listing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='listing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
