# Generated by Django 4.2.23 on 2025-09-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_alter_contact_options_contact_budget_range_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("email_admin", "Email Admin"),
                            ("email_user", "Email User Confirmation"),
                            ("whatsapp", "WhatsApp Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("contact_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
            ],
            options={
                "verbose_name": "Notification Task",
                "verbose_name_plural": "Notification Tasks",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="contacts_no_status_917a6e_idx",
                    ),
                    models.Index(
                        fields=["task_type", "status"],
                        name="contacts_no_task_ty_9aa855_idx",
                    ),
                ],
            },
        ),
    ]
