# Generated by Django 4.2.23 on 2025-09-08 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_notificationqueue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
