# Generated by Django 4.2.23 on 2025-06-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtors", "0002_realtor_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
