# Generated by Django 4.2.23 on 2025-06-23 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("realtors", "0004_realtor_average_rating_realtor_bio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0002_alter_listing_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Property Categories",
            },
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(default="general", max_length=50)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["-list_date"]},
        ),
        migrations.AddField(
            model_name="listing",
            name="cooling",
            field=models.CharField(
                choices=[
                    ("central", "Central Air"),
                    ("window", "Window Units"),
                    ("none", "None"),
                ],
                default="central",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="fireplaces",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="floors",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="listing",
            name="heating",
            field=models.CharField(
                choices=[
                    ("central", "Central"),
                    ("gas", "Gas"),
                    ("electric", "Electric"),
                    ("oil", "Oil"),
                    ("solar", "Solar"),
                    ("none", "None"),
                ],
                default="central",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="hoa_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="listing_type",
            field=models.CharField(
                choices=[("sale", "For Sale"), ("rent", "For Rent")],
                default="sale",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="listing",
            name="parking_spaces",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="property_taxes",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("condo", "Condominium"),
                    ("townhouse", "Townhouse"),
                    ("apartment", "Apartment"),
                    ("loft", "Loft"),
                    ("villa", "Villa"),
                    ("penthouse", "Penthouse"),
                    ("commercial", "Commercial"),
                ],
                default="house",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="year_built",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="bathrooms",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="listing",
            name="lot_size",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("listed", "Listed"),
                            ("price_increase", "Price Increase"),
                            ("price_decrease", "Price Decrease"),
                            ("sold", "Sold"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                ("saves", models.IntegerField(default=0)),
                ("inquiries", models.IntegerField(default=0)),
                ("tours_scheduled", models.IntegerField(default=0)),
                ("last_viewed", models.DateTimeField(blank=True, null=True)),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.propertycategory",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="features",
            field=models.ManyToManyField(blank=True, to="listings.propertyfeature"),
        ),
        migrations.CreateModel(
            name="RealtorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("review_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "realtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="realtors.realtor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("realtor", "user", "listing")},
            },
        ),
        migrations.CreateModel(
            name="ListingView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_records",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("listing", "user", "ip_address")},
            },
        ),
    ]
