# Generated by Django 4.2.23 on 2025-06-24 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0003_propertycategory_propertyfeature_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyModeration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged"),
                            ("under_review", "Under Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("submitted_date", models.DateTimeField(auto_now_add=True)),
                ("reviewed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection or flagging"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal admin notes"),
                ),
                (
                    "report_count",
                    models.IntegerField(default=0, help_text="Number of user reports"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation",
                        to="listings.listing",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Moderation",
                "verbose_name_plural": "Property Moderations",
                "ordering": ["-priority", "-submitted_date"],
            },
        ),
    ]
