# Generated by Django 4.2.23 on 2025-07-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_propertymoderation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="photo_1",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_2",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_3",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_4",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_5",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_6",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_main",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
